In [2]:
import numpy as np

In [3]:
np.random.seed(122345)

In [4]:
np.set_printoptions(precision=4,supress = True)

TypeError: set_printoptions() got unexpected keyword argument 'supress'

In [5]:
data = {1:np.random.randn() for i in range(7)}

data

{1: -0.4851870774725908}

In [6]:
data 

{1: -0.4851870774725908}

In [7]:
1:np.random.randn()

SyntaxError: illegal target for annotation (<ipython-input-7-a98b35ead31c>, line 1)

In [8]:
data = {i:np.random.randn() for i in range(7)}

In [9]:
data

{0: -1.6636153198997836,
 1: 0.22251518531264627,
 2: -0.7019876495578883,
 3: 0.2349805291210785,
 4: -0.3240773824768587,
 5: 1.4343412780962066,
 6: -0.2909333640648452}

In [10]:
'5'+5


TypeError: can only concatenate str (not "int") to str

In [11]:
import csv

In [13]:
%precision 2

'%.2f'

In [17]:
with open ('mpg.csv') as csvfile:
    mpg =list(csv.DictReader(csvfile))

In [18]:
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [19]:
len(mpg)

234

In [21]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [23]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [24]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [25]:
cylinders =set(d['cyl'] for d in mpg)

In [26]:
cylinders

{'4', '5', '6', '8'}

In [32]:
CtyMpgByCyl= []

for c in cylinders:
    summpg=0
    cyltypecount=0
    for  d in mpg :
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg/cyltypecount))

CtyMpgByCyl
            
    

[('8', 12.57), ('5', 20.50), ('4', 21.01), ('6', 16.22)]

In [33]:
CtyMpgByCyl.sort(key=lambda x:x[0])

In [34]:
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [3]:
import datetime as dt
import time as tm 
tm.time()

1619711330.633191

In [9]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2021, 4, 29, 11, 51, 14, 154456)

In [10]:
delta=dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [13]:
today =dt.date.today()
today

datetime.date(2021, 4, 29)

In [15]:
class Person:
    department ='School of Engineering'
    
    def set_name(self,new_name):
        self.name=new_name;
    def set_location(self,location):
        self.location=location

In [20]:
person=Person()
person.name="Jaya"
person.location="Ann Arbor"
print( '{} live in {} and works in he department {}'.format(person.name,person.location,person.department))

Jaya live in Ann Arbor and works in he department School of Engineering


In [22]:
store1 =[10, 11, 12, 1]
store2 = [ 9, 8 ,4 ,5]
cheapest= map(min , store1, store2)
cheapest

In [24]:
people =['Dr. Christopher Brookd', 'Dr. Kevin Collins','Dr. Vinod Vishwan']

def split_title(person):
    a=person.split('.')[0]
    b=person.split(' ')[-1]
    c=a+' '+b
    return c

list(map(split_title,people))

['Dr Brookd', 'Dr Collins', 'Dr Vishwan']

In [25]:
my_function= lambda a,b,c : a+b

In [26]:
my_function(1,2,3)

3

In [27]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [30]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [31]:

l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

NameError: name 'np' is not defined

In [33]:
import numpy as np
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [34]:
a5.shape==a1.shape

True

In [37]:
a1.shape==a2.shape

False

In [38]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

In [39]:
print(old)

[[0 0 1]
 [1 1 1]]


In [43]:
old = np.array([1,2,3])

In [47]:
old[1:2]

array([2])

In [53]:
import re 
s = 'ACBCAC'

re.findall('^AC', s)

['AC']

In [55]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5

In [59]:
d="Office of Research Administration: (734) 647-6333 | 4325 North Quad"

    
[(]\d{3}[)]\d{3}[-]\d{4}
    

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-59-f3b9e4ee02bf>, line 4)

In [60]:
import numpy as np 
import math

In [63]:
a=np.array([1 ,2 ,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [66]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
b.shape

(2, 3)

In [68]:
b.dtype

dtype('int32')

In [69]:
d=np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.random.rand(2,3)

array([[0.35925792, 0.55170759, 0.37462276],
       [0.23165003, 0.02505262, 0.69340887]])

In [73]:
import re 
text ='This is a good day'

In [75]:
if re.search("good",text):
    print('wonderful')
else:
        print("alas")

wonderful


In [76]:
text = "Betty bought a bit of bitter butter . Betty thinks its better butter"
re.split("butter",text)

['Betty bought a bit of bitter ', ' . Betty thinks its better ', '']

In [77]:
re.findall("butter",text)

['butter', 'butter']

In [79]:
len(re.findall("butter",text))

2

In [80]:
text ='ABCABC'
re.search("^AB",text)

<re.Match object; span=(0, 2), match='AB'>

In [81]:
grade="AAAABCAABBCCBBB"
re.findall("B",grade)

['B', 'B', 'B', 'B', 'B', 'B']

In [83]:
re.findall("[AB]",grade)

['A', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'B', 'B', 'B', 'B']

In [94]:
import re
simple_string = "Amy is 5 years old, and her sister Mary is 2 years old.Ruth and Peter, their parents, have 3 kids."
re.findall("[A-Z]{1,100}",simple_string)

['A', 'M', 'R', 'P']

In [110]:
namelist=[]
for each in re.findall("[A-Z]{1,100}",simple_string):
    namelist.append(re.findall(each+"[a-z]{1,100}",simple_string)[0])

In [111]:
namelist 

['Amy', 'Mary', 'Ruth', 'Peter']

In [5]:

import re
string = '''Jaya is 5 years old and Ganesh is 7 years old
,and his grandfather, Oscar is 102.
'''
ages=re.findall('\d{1,3}',string)
names=re.findall('[A-Z][a-z]*',string)
print(ages)
print(names)

ageDict ={}
x=0;
for name in names:
    ageDict[name]=ages[x]
    x=x+1;
print(ageDict)

['5', '7', '102']
['Jaya', 'Ganesh', 'Oscar']
{'Jaya': '5', 'Ganesh': '7', 'Oscar': '102'}


In [12]:
str1="The long boat"
re.findall("^The",str1)

str1="The long boat tend"
re.findall("end$",str1)
re.findall("\wend$",str1)

['tend']

In [53]:
str1="ABABCACAB  ABC ABCC ABCBCBC"
re.findall("ABC*",str1) # ab followed by zero or more c
re.findall("ABC+",str1) #AB followed by one or more C
re.findall("ABC?",str1) #AB followed by zero or one C
re.findall("ABC{2}",str1)#Ab followed by C 2 times
re.findall("ABC{2,}",str1) #Ab foloowed by 2 or more Cs
re.findall("ABC{2,5}",str1)# AB followed by 2 to 5 Cs
re.findall('A(BC)*',str1) # A followed by copies of BC
re.findall('A(BC){2,5}',str1) # A followed by BC 1 to 5 times
re.findall('A(B|C)',str1) # A followed by B or C without capturing A
re.findall('A[BC]',str1) # A followed by B or C with A

['AB', 'AB', 'AC', 'AB', 'AB', 'AB', 'AB']

In [57]:
str2= "hi my number is 123 @ gmail"
re.findall("\d",str2) # matches single character that is a number
re.findall("\d\d",str2) # matched consecutive 2 numbers

['12']

In [60]:
str3 = 'lekshmi_434@hmail.com'
re.findall("@\w",str3) #matches a word characters followed by @

['@h']

In [65]:
str4 = 'Hi this is Jaya'
re.findall("\w*\s",str4) # captures words followed by aspace character
re.findall("\D\D\s",str4) # captures 2 non digit character followed by space

['Hi ', 'is ', 'is ']

In [81]:
str5= "Hi I have $15 and $1 with me "
re.findall("\$\d\d",str5) # matched string that has $ before 2 numeric characters


<function Match.group>

In [114]:
s = "aaa_bbb_xxx_cc_xxx"
print(re.match(r"(?:aaa)(_bbb)", s).group(0)) # returns all matches
print(re.match(r"(?:aaa)(_bbb)", s).group(1)) # capture group
print(re.match(r"(?:aaa)(_bbb)(_xxx)", s).groups()) # all capture groups
print(re.match(r"(?P<g1>aaa)(?P<g2>_bbb)", s).groups()) 

aaa_bbb
_bbb
('_bbb', '_xxx')
('aaa', '_bbb')


In [126]:
# Lazy and greedy match

s= 'This is a <div> simple div</div> test'
re.findall('<.+>',s) # anything other than newline 1 or more times
re.findall('<.+?>',s) #get 1 or more times
re.findall('<[^<>]+>',s) #capture between <> but not < or >

['<div>', '</div>']

In [133]:
# look ahead and look behind

s="third drone"

re.findall('d(?=r)',s) # matches a d only if its is followed by r but r will not be part of overalll regex match
re.findall('(?<=r)d',s) # matched a d only if it is preceded by and r but r wil not be part of the overall regex match

['d']